(()=>{
'use strict';
const groups=[['semblanca','Figures i cossos semblants'],['tales','Teorema de Tales'],['triangles','Triangles semblants'],['posicio-tales','Triangles en posició de Tales'],['catet','Teorema del catet'],['altura','Teorema de l’altura'],['pitagores','Teorema de Pitàgores'],['longitud','Raó de longitud'],['area','Raó d’àrea'],['volum','Raó de volum'],['barrejats','Problemes barrejats']];
const triangleTopics=[['semblanca','1. Figures i cossos semblants'],['triangles','2. Triangles semblants'],['tales','3. Teorema de Tales'],['posicio-tales','4. Posició de Tales']];
const ratioTopics=[['longitud','1. Raó de longitud'],['area','2. Raó d’àrea'],['volum','3. Raó de volum']];
const sectionTitles={triangles:'Triangles semblants',teoremes:'Teoremes',raons:'Raó de semblança',problemes:'Problemes'};
const theoremTopics=[['catet','1. Teorema del catet'],['altura','2. Teorema de l’altura'],['pitagores','3. Teorema de Pitàgores']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const txt=s=>esc(s).replace(/&lt;sub&gt;(.*?)&lt;\/sub&gt;/g,'<sub>$1</sub>').replace(/&lt;b&gt;(.*?)&lt;\/b&gt;/g,'<strong>$1</strong>');
function math(x,calculation=false){
 if(typeof x==='string'||typeof x==='number')return txt(x);
 if(x[0]==='frac'){
  if(calculation){
   const operand=value=>{const rendered=math(value,true);return typeof value==='string'&&!/[+−=·:]| - /.test(value)?rendered:`(${rendered})`;};
   return `${operand(x[1])} : ${operand(x[2])}`;
  }
  return `<span class="frac"><span>${math(x[1])}</span><span>${math(x[2])}</span></span>`;
 }
 if(x[0]==='root')return `<span class="root">${x[2]===3?'<sup>3</sup>':''}<span class="root-symbol">√</span><span class="radicand">${math(x[1],calculation)}</span></span>`;
 return x.map(value=>math(value,calculation)).join('');
}
function svg(inner,label,box='0 0 540 290'){return `<svg viewBox="${box}" role="img" aria-label="${esc(label)}">${inner}</svg>`;}
function homeArt(){return svg('<path class="blue" d="M35 220H175L105 115Z"/><path class="teal" d="M235 220H515L375 10Z"/><text x="105" y="260" text-anchor="middle">Figura inicial</text><text x="375" y="260" text-anchor="middle">Figura ampliada</text>','Dos triangles amb la mateixa forma. El segon té els costats el doble de llargs.');}
function guide(message){return `<aside class="guide" aria-label="Consell de la Guspira"><img src="assets/guspira.png" width="115" height="155" alt="La Guspira, científica amb bata i escaire"><div><div class="guide-name">LA GUSPIRA T’ACOMPANYA</div><p>${message}</p></div></aside>`;}
function escapeBanner(){return `<section class="escape-banner" aria-labelledby="escape-title"><img src="assets/escape-illa.png" width="1672" height="941" alt="Una illa de còmic amb arbres geomètrics, un pont i un far" loading="lazy"><div><p class="escape-kicker">NOVA AVENTURA · ESCAPE ROOM</p><h2 id="escape-title">L’illa de les proporcions</h2><p>Cinc portes. Cinc proves curtes. Ajuda la Guspira a arribar al far i descobreix què vol dir <strong>canviar de mida sense canviar de forma</strong>.</p><p>Amb dibuixos, dues ajudes i una explicació a cada prova. <strong>Sense límit de temps.</strong></p><a class="escape-btn" href="escape-room.html" target="_blank" rel="noopener" id="escape-launch">Entra a l’Escape Room ↗</a><p class="new-window-note">S’obre en una finestra nova. El navegador també pot obrir-lo en una pestanya.</p><p id="escape-fallback" class="new-window-note" hidden>Si el joc no s’ha obert, <a href="escape-room.html">obre’l aquí</a>.</p></div></section>`;}
function home(){return `<main id="main" class="home"><section class="home-intro"><div><div class="mission-badge">L’illa de la geometria</div><h1>Geometria<br>pas a pas</h1><p>Recorre l’illa amb la Guspira. A cada missió descobrirem una idea de geometria, mirarem un exemple i repetirem el procediment.</p><p><strong>Un pas cada vegada. Al teu ritme.</strong></p></div><div class="home-art"><div class="mission-art"><img src="assets/guspira.png" width="140" height="190" alt="La Guspira, la nostra guia científica"><div><h2>Comencem amb una idea</h2><p>Dos triangles poden tenir <strong>la mateixa forma</strong> i una mida diferent.</p><p class="proportional-intro">Les longituds corresponents són <strong>proporcionals</strong> quan totes es multipliquen pel <strong>mateix nombre</strong>.</p><p class="proportional-intro">Aquí, <strong>cada costat del segon triangle és el doble</strong> del costat corresponent del primer. Tots canvien pel mateix factor: <strong>2</strong>.</p></div></div>${homeArt()}<div class="art-caption"><span>Observa els costats</span><span class="pill">Compara les formes</span></div></div></section>${escapeBanner()}<section aria-labelledby="path-title"><div class="section-heading"><h2 id="path-title">La teva ruta per l’illa</h2><p>Pots tornar a qualsevol missió.</p></div><div class="path-grid"><article class="path-card"><span class="number">ZONA 1 · OBSERVA I COMPARA</span><h3>Triangles semblants</h3><p>Figures semblants, triangles, Tales i posició de Tales.</p><a href="#triangles/semblanca">Comença la primera missió</a></article><article class="path-card" style="--card-color:var(--teal)"><span class="number">ZONA 2 · TROBA UNA MESURA</span><h3>Teoremes</h3><p>Catet, altura i Pitàgores. Aprèn quan i com utilitzar cada fórmula.</p><a href="#teoremes/catet">Explora els teoremes</a></article><article class="path-card" style="--card-color:var(--purple)"><span class="number">ZONA 3 · AMPLIA I REDUEIX</span><h3>Raó de semblança</h3><p>Raó de longitud i la seva aplicació a les escales. Raó d’àrea i de volum.</p><a href="#raons/longitud">Explora les raons de semblança</a></article><article class="path-card" style="--card-color:var(--orange)"><span class="number">ZONA 4 · REPETEIX ELS PASSOS</span><h3>Problemes de tot tipus</h3><p>70 problemes amb dades, resolució i resposta final.</p><a href="#problemes/semblanca">Mira els problemes resolts</a></article></div></section>${guide('A cada missió, primer t’explico una idea. Després mirem un exemple junts. Finalment, pots seguir altres problemes resolts amb els mateixos passos.')}</main>`;}
function sidebar(section,current,anchor=''){
 const topics=section==='triangles'?triangleTopics:section==='teoremes'?theoremTopics:section==='raons'?ratioTopics:groups;
 const title=sectionTitles[section]||'Problemes';
 return `<aside class="sidebar"><p class="sidebar-label">${title}</p><nav class="topic-nav${section==='raons'?' ratio-nav':''}" aria-label="Apartats de ${title.toLowerCase()}">${topics.map(([id,title])=>{
  const link=`<a href="#${section}/${id}"${current===id?' aria-current="page"':''}>${title}</a>`;
  return section==='raons'&&id==='longitud'?`<div class="topic-group">${link}<a class="subtopic" href="#raons/longitud/escales"${anchor==='escales'?' aria-current="location"':''}>Aplicació: escales</a></div>`:link;
 }).join('')}</nav></aside>`;
}
function caption(p,i){const k=p.check[0];const map={catet:['Substituïm les dades i multipliquem.','Fem l’arrel quadrada del producte.'],height:['Substituïm m i n. Multipliquem.','Fem l’arrel quadrada del producte.'],pyth:['Substituïm els catets a la fórmula.','Calculem els quadrats i els sumem.','Fem l’arrel quadrada.'],missing:['Substituïm la hipotenusa i el catet conegut.','Calculem els quadrats i restem.','Fem l’arrel quadrada.'],area:['Substituïm l’àrea inicial i la raó.','Calculem el quadrat de la raó i multipliquem.'],volume:['Substituïm el volum inicial i la raó.','Calculem el cub de la raó i multipliquem.'],rootratio:['Dividim la mesura final entre la inicial.','Fem l’arrel '+(+p.check[3]===2?'quadrada.':'cúbica.')],scale:['Substituïm l’escala i la mesura del dibuix.','Multipliquem per trobar la longitud real.','Convertim a la unitat que ens demanen.'],tales:['Substituïm les dades a la proporció.','Multipliquem en creu.','Dividim per trobar x.'],nested:['Escrivim la proporció amb les dades.','Multipliquem i dividim per trobar x.'],shadow:['Relacionem altura i ombra de cada triangle.','Multipliquem i dividim per trobar l’altura.']};return map[k]?.[i]||'';}
function problem(p,open=false){if(!p)return '';const drawing=window.GEOMETRIA_DIAGRAM?window.GEOMETRIA_DIAGRAM(p):'';return `<article class="problem" id="problema-${p.number}"><div class="problem-top"><div class="problem-label">Problema ${p.number}</div><p class="q">${txt(p.q)}</p>${drawing?`<div class="problem-figure">${drawing}</div>`:''}<p class="solution-line"><strong>Solució:</strong> ${txt(p.answer)}</p></div><details${open?' open':''}><summary>Resolució pas a pas</summary><div class="resolution"><h4>Dades</h4><ul>${p.data.map(d=>`<li>${txt(d)}</li>`).join('')}</ul><h4>Resolució</h4><p>Escrivim la fórmula que necessitem.</p><div class="formula"><span class="formula-inner">${math(p.formula)}</span></div><ol class="step-list">${p.steps.map((s,i)=>`<li><div>${caption(p,i)?`<span class="step-caption">${caption(p,i)}</span>`:''}<span class="equation">${math(s,true)}</span></div></li>`).join('')}</ol><h4>Solució</h4><p class="answer">${txt(p.answer)}</p></div></details></article>`;}
function scaleApplication(){
 const l=window.GEOMETRIA_LESSONS.escales;
 const ps=l.problems.map(n=>window.GEOMETRIA_PROBLEMS.find(p=>p.number===n));
 return `<section id="escales" class="lesson-section scale-application" tabindex="-1"><header class="application-head"><p class="breadcrumb">Raó de longitud · Aplicació</p><h2>Escales: dibuix i realitat</h2><p>Utilitzem la <strong>raó de longitud</strong> per relacionar les mesures d’un plànol, un mapa o una maqueta amb les mesures reals.</p></header>${guide(l.tip)}<div class="panel"><h3>Del dibuix a la realitat</h3><p>Prenem el dibuix com a figura inicial i la realitat com a figura final.</p><p>A escala <strong>1:100</strong>, el factor per passar del dibuix a la realitat és <strong>100</strong>. Multipliquem la longitud del dibuix per 100.</p><div class="formula"><span class="formula-inner">${math(['Raó<sub>Long</sub> = ',['frac','longitud real','longitud dibuix']])}</span></div><div class="formula"><span class="formula-inner">${math('longitud real = longitud dibuix · Raó<sub>Long</sub>')}</span></div><p>L’escala <strong>1:100</strong> expressa la relació en l’altre sentit: dibuix respecte de realitat.</p></div>${l.body}<div class="panel"><h3>Seguim aquests passos</h3><ol class="step-list">${l.steps.map(step=>`<li><div>${step}</div></li>`).join('')}</ol></div><h3>Exemple resolt d’escales</h3>${problem(ps[0],true)}<h3>Un altre exercici resolt d’escales</h3>${ps.slice(1).map(p=>problem(p)).join('')}<p><a href="#raons/longitud">Torna a la raó de longitud</a></p></section>`;
}
function lesson(section,id,anchor=''){
 const l=window.GEOMETRIA_LESSONS[id];if(!l||l.section!==section)return notFound();
 const problems=l.problems.map(n=>window.GEOMETRIA_PROBLEMS.find(p=>p.number===n));
 const hasScales=section==='raons'&&id==='longitud';
 return `<div class="layout">${sidebar(section,id,anchor)}<main id="main" class="content" tabindex="-1"><header class="lesson-head"><p class="breadcrumb">L’illa de la geometria · ${sectionTitles[section]}</p><h1>${l.title}</h1><p>${l.lead}</p><nav class="lesson-index" aria-label="Dins d’aquest apartat"><a href="#teoria">Teoria</a><a href="#exemple">Exemple resolt</a><a href="#exercicis">Exercicis resolts</a>${hasScales?'<a href="#raons/longitud/escales">Aplicació: escales</a>':''}</nav></header>${guide(l.tip||'Abans de calcular, comprova què coneixes i què busques. Fes una operació cada vegada.')}<section id="teoria" class="lesson-section">${l.body}<div class="panel"><h3>Seguim aquests passos</h3><ol class="step-list">${l.steps.map(s=>`<li><div>${s}</div></li>`).join('')}</ol></div></section><section id="exemple" class="lesson-section"><h2>La Guspira resol un exemple</h2>${problem(problems[0],true)}</section><section id="exercicis" class="lesson-section"><h2>Repetim el procediment</h2><p>Observa les dades. Pots obrir la resolució de cada problema.</p>${problems.slice(1).map(p=>problem(p)).join('')}</section>${hasScales?scaleApplication():''}<div class="lesson-end"><a href="#problemes/${id}">Mira els problemes d’aquest tema</a><a href="#inici">Torna a l’inici</a></div></main></div>`;
}
const practiceLevels=[['C','Comencem a poc a poc','Casos directes per reconèixer i aplicar una idea.'],['B','Fem un pas més','Dades desconegudes i aplicacions a situacions quotidianes.'],['A','Connectem les idees','Problemes amb més passos o que demanen comparar i decidir.']];
function practiceNav(){return `<nav class="practice-nav" aria-label="Ves als problemes de pràctica"><span>15 problemes per practicar</span>${practiceLevels.map(([level])=>`<button type="button" class="practice-jump" data-practice-target="practica-${level.toLowerCase()}">Grup ${level} · 5 problemes</button>`).join('')}</nav>`;}
function practiceBank(id){const levels=window.GEOMETRIA_PRACTICE?.[id];if(!levels)return '';return `<section class="practice-bank" aria-labelledby="practica-titol"><header class="practice-intro"><h2 id="practica-titol">Ara et toca a tu!</h2><p>15 problemes nous, de menys a més dificultat. Pots començar pel <strong>grup C</strong>, continuar amb el <strong>grup B</strong> i acabar amb el <strong>grup A</strong>.</p><p>Intenta resoldre cada problema abans de mirar la <strong>solució</strong>. Aquí trobaràs la resposta final per comprovar-la.</p></header>${practiceLevels.map(([level,title,description])=>`<section class="practice-level" data-level="${level}" aria-labelledby="practica-${level.toLowerCase()}-titol"><header class="practice-level-head" id="practica-${level.toLowerCase()}" tabindex="-1"><h3 id="practica-${level.toLowerCase()}-titol">Grup ${level} · ${title}</h3><p>5 problemes · ${description}</p></header>${levels[level].map((p,i)=>`<article class="practice-problem" aria-labelledby="practica-${level.toLowerCase()}-${i+1}"><h4 id="practica-${level.toLowerCase()}-${i+1}">Problema ${level}${i+1}</h4><p class="q">${txt(p.q)}</p><p class="solution-line"><strong>Solució: ${txt(p.answer)}</strong></p></article>`).join('')}</section>`).join('')}</section>`;}
function problemPage(id){const idx=groups.findIndex(g=>g[0]===id);if(idx<0)return notFound();const ps=window.GEOMETRIA_PROBLEMS.filter(p=>idx===10?p.number>50:p.number>idx*5&&p.number<=(idx+1)*5);return `<div class="layout">${sidebar('problemes',id)}<main id="main" class="content" tabindex="-1"><header class="lesson-head"><p class="breadcrumb">L’illa de la geometria · Problemes de tot tipus</p><h1>${groups[idx][1]}</h1><p class="topic-total">${ps.length} problemes resolts · 15 problemes de pràctica</p></header>${guide('Llegeix cada enunciat amb calma. Obre les resolucions per seguir els passos dels exemples. Al final, practica amb els grups C, B i A i comprova la resposta final.')}${practiceNav()}<section aria-label="Problemes resolts">${ps.map(p=>problem(p)).join('')}</section>${practiceBank(id)}<div class="lesson-end">${idx<10?`<a href="#problemes/${groups[idx+1][0]}">Continua amb ${groups[idx+1][1].toLowerCase()}</a>`:'<a href="#problemes/semblanca">Torna al primer grup</a>'}<a href="#inici">Torna a l’inici</a></div></main></div>`;}
function notFound(){return `<main id="main" class="home"><h1>Apartat no trobat</h1><p><a href="#inici">Torna a l’inici</a></p></main>`;}
function render(){
 const raw=location.hash.slice(1)||'inici';
 if(['teoria','exemple','exercicis','main'].includes(raw)){document.getElementById(raw)?.scrollIntoView();return;}
 let [section,id,anchor]=raw.split('/');
 // Preserve old links after moving the ratio lessons out of Triangles.
 if(section==='triangles'&&['longitud','escales','area','volum'].includes(id))section='raons';
 if(section==='raons'&&id==='escales'){id='longitud';anchor='escales';}
 if(section==='raons'&&!id)id='longitud';
 const canonical=section==='inici'?'inici':[section,id,anchor].filter(Boolean).join('/');
 if(canonical!==raw)history.replaceState(null,'',`#${canonical}`);
 document.querySelectorAll('[data-tab]').forEach(a=>a.dataset.tab===section?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current'));
 document.getElementById('app').innerHTML=section==='inici'?home():section==='problemes'?problemPage(id):lesson(section,id,anchor);
 const title=anchor==='escales'?'Escales · Raó de longitud':section==='problemes'?groups.find(g=>g[0]===id)?.[1]:window.GEOMETRIA_LESSONS[id]?.title;
 document.title=section==='inici'?'Geometria pas a pas':(title||'Geometria')+' · Geometria pas a pas';
 window.scrollTo(0,0);
 if(anchor==='escales'&&section==='raons'&&id==='longitud')document.getElementById('escales')?.scrollIntoView({block:'start'});
}
function escapeWindowFeatures(){
 const screen=window.screen;
 const availableWidth=screen.availWidth||screen.width;
 const availableHeight=screen.availHeight||screen.height;
 const width=Math.min(1180,Math.max(1,availableWidth-32));
 const height=Math.min(850,Math.max(1,availableHeight-80));
 const originLeft=Number.isFinite(screen.availLeft)?screen.availLeft:0;
 const originTop=Number.isFinite(screen.availTop)?screen.availTop:0;
 const left=Math.round(originLeft+(availableWidth-width)/2);
 const top=Math.round(originTop+(availableHeight-height)/2);
 return `popup,width=${width},height=${height},left=${left},top=${top}`;
}
document.addEventListener('click',e=>{if(e.target.closest('#escape-launch')&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){document.getElementById('escape-fallback').hidden=false;const gameWindow=window.open('escape-room.html?popup=1','_blank',escapeWindowFeatures());if(gameWindow){gameWindow.opener=null;e.preventDefault();}return;}const a=e.target.closest('a[href]');if(a&&['#teoria','#exemple','#exercicis','#main'].includes(a.getAttribute('href'))){e.preventDefault();document.querySelector(a.getAttribute('href'))?.scrollIntoView();}});
window.addEventListener('hashchange',render);render();
document.addEventListener('click',e=>{const button=e.target.closest('[data-practice-target]');if(!button)return;const target=document.getElementById(button.dataset.practiceTarget);if(target){target.focus({preventScroll:true});target.scrollIntoView({block:'start'});}});
window.GEOMETRIA_RENDER_MATH=math;
})();
