(()=>{
const F=(a,b)=>['frac',a,b],R=(a,p=2)=>['root',a,p];
function M(x){if(typeof x==='string')return x;if(x[0]==='frac')return `<span class="frac"><span>${M(x[1])}</span><span>${M(x[2])}</span></span>`;if(x[0]==='root')return `<span class="root">${x[2]===3?'<sup>3</sup>':''}<span class="root-symbol">√</span><span class="radicand">${M(x[1])}</span></span>`;return x.map(M).join('');}
const f=x=>`<div class="formula"><span class="formula-inner">${M(x)}</span></div>`;
const panel=(t,b)=>`<div class="panel"><h2>${t}</h2>${b}</div>`;
const note=(t,b,w=false)=>`<aside class="note${w?' warning':''}"><h3>${t}</h3><p>${b}</p></aside>`;
const legend=rows=>`<h3>Què vol dir cada cosa?</h3><dl class="legend">${rows.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`;
const S=(b,l,v='0 0 540 310')=>`<figure><svg viewBox="${v}" role="img" aria-label="${l}">${b}</svg><figcaption class="figure-caption">Dibuix orientatiu. Les dades escrites són les que utilitzem per calcular.</figcaption></figure>`;
const rects=S('<rect class="blue" x="50" y="150" width="120" height="80"/><rect class="teal" x="250" y="70" width="240" height="160"/><text x="110" y="263" text-anchor="middle">4 cm</text><text x="45" y="195" text-anchor="end">3</text><text x="370" y="263" text-anchor="middle">8 cm</text><text x="243" y="156" text-anchor="end">6</text>','Rectangles semblants de 4 per 3 centímetres i 8 per 6 centímetres.');
const triangles=S('<path class="blue" d="M45 230H195L45 118Z"/><path class="teal" d="M260 230H500L260 50Z"/><text x="120" y="265" text-anchor="middle">b</text><text x="37" y="174" text-anchor="end">c</text><text x="139" y="161">a</text><text x="380" y="265" text-anchor="middle">b′</text><text x="250" y="151" text-anchor="end">c′</text><text x="405" y="118">a′</text><path class="line" d="M45 216H59V230 M260 215H275V230"/>','Triangles semblants: parelles de costats a i a prima, b i b prima, c i c prima.');
const tales=S('<path class="line" d="M50 74H505 M50 148L505 236"/><path class="accent" d="M80 35V255 M220 35V255 M465 35V285"/><text x="150" y="58" text-anchor="middle">a</text><text x="342" y="58" text-anchor="middle">a′</text><text x="143" y="194" text-anchor="middle">b</text><text x="340" y="246" text-anchor="middle">b′</text>','Tres paral·leles tallen dues secants. a i a prima són segments consecutius de la primera secant, b i b prima els homòlegs de la segona.');
const nested=S('<path class="teal" d="M60 230H480L340 40Z"/><path class="blue" d="M60 230H270L200 135Z"/><path class="accent" d="M270 230L200 135 M480 230L340 40"/><text x="117" y="173">a</text><text x="159" y="260">b</text><text x="239" y="104">a′</text><text x="371" y="260">b′</text><path class="line" d="M68 294H480"/><text x="274" y="318" text-anchor="middle">base gran sencera</text>','Triangle petit dins del gran. a i b són costat i base del petit; a prima i b prima són els costats sencers del gran. Els costats drets són paral·lels.','0 0 540 340');
const right=S('<path class="teal" d="M105 230H455L105 65Z"/><path class="line" d="M105 208H127V230"/><text x="275" y="271" text-anchor="middle">b · catet</text><text x="18" y="146">c</text><text x="21" y="173">catet</text><text x="287" y="125">a · hipotenusa</text><text x="139" y="218">90°</text>','Triangle rectangle. b i c són els catets. a és la hipotenusa oposada a l’angle recte.');
const altitude=S('<path class="teal" d="M65 240H485L216.2 38.4Z"/><path class="accent" d="M216.2 38.4V240"/><path class="line" d="M216.2 221H235.2V240 M205.4 52.8L219.8 63.6L230.6 49.2"/><text x="139" y="277" text-anchor="middle">m</text><text x="350" y="277" text-anchor="middle">n</text><text x="235" y="157">h</text><text x="114" y="127">b</text><text x="365" y="127">c</text><path class="line" d="M65 308H485"/><text x="276" y="337" text-anchor="middle">a = m + n</text>','Triangle rectangle. L’altura h divideix a en m i n. El catet b correspon a m; el catet c a n.','0 0 540 355');
const squares=S('<rect class="blue" x="55" y="165" width="80" height="80"/><rect class="teal" x="285" y="85" width="160" height="160"/><path class="line" d="M365 85V245 M285 165H445"/><text x="95" y="280" text-anchor="middle">1 quadrat</text><text x="365" y="280" text-anchor="middle">4 quadrats</text>','En duplicar el costat d’un quadrat, hi caben quatre quadrats inicials.');
const cube=(x,y,s)=>{let d=s*.3;return `<path class="teal" d="M${x} ${y}h${s}v${s}h-${s}Z M${x} ${y}l${d} -${d}h${s}l-${d} ${d}Z M${x+s} ${y}l${d} -${d}v${s}l-${d} ${d}Z"/>`;};
const cubes=S(cube(65,155,65)+cube(290,105,130)+'<text x="102" y="274" text-anchor="middle">Cub inicial</text><text x="370" y="274" text-anchor="middle">Costat doble</text>','Quan el costat d’un cub es duplica, el volum es multiplica per vuit.');

const homologousExample=`<section class="similarity-example" id="exemple-homolegs"><h3>Exemple: què correspon a què?</h3><p>El triangle gran és una ampliació del petit. Busca <strong>el mateix color i la mateixa posició</strong>.</p>
<figure><svg viewBox="0 0 680 340" role="img" aria-label="Triangles rectangles ABC i A prima B prima C prima. AB fa 4 cm i A prima B prima 8; AC fa 3 i A prima C prima 6; BC fa 5 i B prima C prima 10. Tots els costats es dupliquen i els angles corresponents són iguals.">
<text x="155" y="30" text-anchor="middle">Triangle inicial</text><text x="480" y="30" text-anchor="middle">Triangle ampliat</text>
<path d="M85 250H205L85 160Z M360 250H600L360 70Z" fill="#e8f7f3" stroke="#152840" stroke-width="2"/>
<path d="M85 250H205 M360 250H600" fill="none" stroke="#1749b0" stroke-width="5"/>
<path d="M85 250V160 M360 250V70" fill="none" stroke="#006b61" stroke-width="5"/>
<path d="M85 160L205 250 M360 70L600 250" fill="none" stroke="#a44605" stroke-width="5"/>
<path d="M85 232H103V250 M360 232H378V250" fill="none" stroke="#6437a2" stroke-width="3"/>
<path d="M185 250A20 20 0 0 1 189 238 M580 250A20 20 0 0 1 584 238" fill="none" stroke="#1749b0" stroke-width="3"/>
<path d="M85 185A25 25 0 0 0 105 175 M360 95A25 25 0 0 0 380 85" fill="none" stroke="#006b61" stroke-width="3"/>
<text x="68" y="281" class="angle-a">A</text><text x="208" y="281" class="angle-b">B</text><text x="70" y="147" class="angle-c">C</text>
<text x="343" y="281" class="angle-a">A′</text><text x="602" y="281" class="angle-b">B′</text><text x="342" y="58" class="angle-c">C′</text>
<text x="145" y="285" text-anchor="middle">4 cm</text><text x="480" y="285" text-anchor="middle">8 cm</text>
<text x="65" y="212" text-anchor="end">3 cm</text><text x="341" y="165" text-anchor="end">6 cm</text>
<text x="163" y="192">5 cm</text><text x="500" y="147">10 cm</text>
<text x="110" y="230" class="angle-a">90°</text><text x="385" y="230" class="angle-a">90°</text>
</svg><figcaption>AB ↔ A′B′ · AC ↔ A′C′ · BC ↔ B′C′</figcaption></figure>
<div class="homologous-pairs"><p><b>Base blava:</b> 4 → 8 cm, <strong>· 2</strong>.</p><p><b>Costat verd:</b> 3 → 6 cm, <strong>· 2</strong>.</p><p><b>Costat taronja:</b> 5 → 10 cm, <strong>· 2</strong>.</p></div><p>Els angles corresponents són <strong>A i A′, B i B′, C i C′</strong>. Cada parella té la mateixa obertura. Per exemple, A i A′ fan <strong>90°</strong>.</p></section>`;
const deformationExample=`<section class="similarity-example" id="exemple-deformacio"><h3>Exemple: ampliar o deformar?</h3><p>Partim d’un rectangle de <strong>4 cm de base i 2 cm d’altura</strong>.</p>
<figure><svg viewBox="0 0 680 340" role="img" aria-label="Rectangle inicial de 4 per 2 centímetres, ampliació proporcional de 8 per 4, i rectangle deformat de 8 per 6. En l'ampliació tots dos costats es dupliquen. En la deformació la base es duplica i l'altura es triplica.">
<text x="120" y="35" text-anchor="middle">Inicial</text><text x="325" y="35" text-anchor="middle">Mateixa forma</text><text x="545" y="35" text-anchor="middle">Deformat</text>
<rect x="80" y="210" width="80" height="40" fill="#eaf1ff" stroke="#1749b0" stroke-width="3"/>
<rect x="245" y="170" width="160" height="80" fill="#cbf0e7" stroke="#006b61" stroke-width="3"/>
<rect x="465" y="130" width="160" height="120" fill="#ffe6b4" stroke="#a44605" stroke-width="3"/>
<text x="120" y="280" text-anchor="middle">4 cm</text><text x="65" y="236" text-anchor="end">2</text>
<text x="325" y="280" text-anchor="middle">8 cm</text><text x="230" y="217" text-anchor="end">4</text>
<text x="545" y="280" text-anchor="middle">8 cm</text><text x="450" y="197" text-anchor="end">6</text>
<text x="325" y="90" text-anchor="middle">Base · 2</text><text x="325" y="119" text-anchor="middle">Altura · 2</text>
<text x="545" y="90" text-anchor="middle">Base · 2</text><text x="545" y="119" text-anchor="middle">Altura · 3</text>
</svg><figcaption>Els tres rectangles estan dibuixats amb la mateixa escala. Mesures en centímetres.</figcaption></figure>
<div class="deformation-comparison"><p><strong>4 · 2 = 8 i 2 · 2 = 4.</strong><br>El mateix factor: <strong>sí que són semblants</strong>.</p><p><b>4 · 2 = 8, però 2 · 3 = 6.</b><br>Factors diferents: <b>no són semblants</b>. El rectangle queda més alt en relació amb la base.</p></div></section>`;

const rl='Raó<sub>Long</sub>',ra='Raó<sub>Àrea</sub>',rv='Raó<sub>Volum</sub>';
window.GEOMETRIA_LESSONS={
semblanca:{section:'triangles',title:'Figures i cossos semblants',lead:'Missió 1 · Descobreix què canvia i què es manté.',body:panel('La mateixa forma',`<div class="concept-grid"><div><p>Dues figures són semblants quan tenen <strong>la mateixa forma</strong>. Poden tenir mides diferents.</p><p>Una ampliació o una reducció canvia la mida sense deformar la figura.</p></div>${rects}</div>`)+panel('Dues condicions',`<ol class="step-list"><li><div>Els <strong>angles homòlegs són iguals</strong>.</div></li><li><div>Els <strong>costats homòlegs són proporcionals</strong>: tots canvien amb el mateix factor.</div></li></ol>`+note('Homòleg vol dir corresponent','Són els costats o angles que ocupen la mateixa posició. Mira la forma abans de comparar les mesures.')+homologousExample)+panel('Figures planes i cossos',`<p>Un <strong>rectangle</strong> és una figura plana. Té superfície.</p><p>Un <strong>cub</strong> és un cos. Ocupa espai i té volum.</p><p>Tots els quadrats són semblants entre si. Tots els cercles també. Tots els cubs són semblants entre si.</p>`+note('Atenció','Dos rectangles no són sempre semblants. Si un costat es duplica però l’altre es triplica, la forma queda deformada.',true)+deformationExample),steps:['Busca els costats homòlegs.','Comprova que els angles homòlegs són iguals.','Divideix cada costat final pel seu costat inicial.','Si tots els resultats són iguals, els costats són proporcionals.'],problems:[1,2,3,4,5],tip:'Si només canvia la mida, pot ser una semblança. Si s’estira més en una direcció que en una altra, la figura es deforma.'},
longitud:{section:'raons',title:'Raó de semblança de longitud',lead:'Missió 8 · Descobreix per quant es multipliquen els costats.',body:panel('Una raó és una divisió',`<p>Una <strong>raó</strong> compara dues quantitats. Per comparar 6 cm amb 3 cm, dividim 6 entre 3.</p>${f('6 cm : 3 cm = 2')}<p>El resultat 2 vol dir que la primera longitud és <strong>el doble</strong> de la segona.</p>`)+panel('Comparem longituds',`<p>La ${rl} indica per quant multipliquem la longitud inicial per obtenir la final.</p>${f([rl+' = ',F('longitud final','longitud inicial')])}${f(['longitud final = longitud inicial · '+rl])}`+legend([[rl,'Factor pel qual es multipliquen les longituds. No té unitats.'],['longitud inicial','Mesura del costat de la figura de partida.'],['longitud final','Mesura del costat homòleg de la figura final.']])+note('Abans de dividir','Les longituds han d’estar en la mateixa unitat. Converteix-les abans de calcular.'))+panel('Ampliem o reduïm?',`<ul><li>Si <strong>${rl} &gt; 1</strong>, ampliem.</li><li>Si <strong>0 &lt; ${rl} &lt; 1</strong>, reduïm.</li><li>Si <strong>${rl} = 1</strong>, les mides són iguals.</li></ul>${rects}`),steps:['Escriu la longitud inicial i la final del mateix costat homòleg.','Posa les mesures en la mateixa unitat.','Divideix la longitud final entre la inicial.','Per calcular un altre costat final, multiplica la seva longitud inicial per la raó.'],problems:[36,37,38,39,40],tip:'L’ordre és important: final a dalt, inicial a baix. Una ampliació dona una raó més gran que 1.'},
triangles:{section:'triangles',title:'Triangles semblants',lead:'Missió 2 · Comprova si dos triangles tenen la mateixa forma.',body:panel('Què ha de passar?',`<p>Han de tenir <strong>angles homòlegs iguals</strong> i <strong>costats homòlegs proporcionals</strong>.</p>${triangles}${f([F('a','a′'),' = ',F('b','b′'),' = ',F('c','c′')])}`+legend([['a, b, c','Costats del primer triangle.'],['a′, b′, c′','Costats homòlegs del segon. El signe ′ es llegeix «prima».']]))+panel('Tres maneres de comprovar-ho',`<div class="criteria"><article class="criterion"><h3>AA · Dos angles iguals</h3><p>Si dos angles d’un triangle són iguals a dos angles de l’altre, <strong>els triangles són semblants</strong>.</p><p>El tercer angle també coincideix: els tres angles sumen 180°.</p></article><article class="criterion"><h3>CCC · Tres costats proporcionals</h3><p>Comparem els tres parells de costats homòlegs. Si els tres quocients són iguals, <strong>els triangles són semblants</strong>.</p></article><article class="criterion"><h3>CAC · Dos costats i l’angle entre ells</h3><p>Dos parells de costats homòlegs són proporcionals. L’angle <strong>comprès entre aquests costats</strong> és igual als dos triangles.</p></article></div>`)+note('Compara els costats corresponents','Marca les parelles homòlogues abans de dividir. No barregis les parelles.',true),steps:['Identifica els angles o costats que coneixes.','Busca les parelles homòlogues.','Tria AA, CCC o CAC segons les dades.','Comprova totes les condicions del criteri.'],problems:[11,12,13,14,15],tip:'No decideixis només mirant el dibuix. Les mesures i els angles permeten comprovar la semblança.'},
tales:{section:'triangles',title:'Teorema de Tales',lead:'Missió 3 · Utilitza les paral·leles per trobar un segment.',body:panel('Paral·leles i secants',`<p>Les <strong>rectes paral·leles</strong> mantenen la mateixa direcció i no es tallen.</p><p>Una <strong>recta secant</strong> talla altres rectes.</p>${tales}<p>Quan unes paral·leles tallen dues secants, els segments homòlegs són <strong>proporcionals</strong>.</p>`)+panel('La fórmula',f([F('a','b'),' = ',F('a′','b′')])+legend([['a i a′','Segments consecutius d’una de les secants.'],['b i b′','Segments homòlegs de l’altra secant.'],['x','Mesura desconeguda.']])+note('Mantén l’ordre','a correspon a b. a′ correspon a b′. Escriu els dos quocients seguint el mateix ordre.'))+panel('Com trobem x?',`<p>Si b′ és x:</p>${f([F('a','b'),' = ',F('a′','x')])}${f(['a · x = a′ · b'])}${f(['x = ',F('a′ · b','a')])}<p>Multipliquem <strong>en creu</strong>. Després dividim pel nombre que multiplica x.</p>`),steps:['Comprova que les rectes que tallen les secants són paral·leles.','Marca els segments homòlegs a, b, a′ i b′.','Escriu la proporció i substitueix les dades.','Multiplica en creu i divideix per trobar x.'],problems:[6,7,8,9,10],tip:'Segueix les secants amb el dit. Busca els segments que queden entre les mateixes paral·leles.'},
'posicio-tales':{section:'triangles',title:'Triangles en posició de Tales',lead:'Missió 4 · Compara el triangle petit i el triangle gran.',body:panel('Com els reconeixem?',`<p>Tenen <strong>un vèrtex comú</strong>. Dos costats del triangle petit estan sobre els del gran.</p><p>El tercer costat del petit és <strong>paral·lel</strong> al tercer costat del gran.</p>${nested}<p>Aquests triangles són <strong>semblants</strong>.</p>`)+panel('Comparem els costats sencers',`${f([F('a','b'),' = ',F('a′','b′')])}${f([F('costat gran','costat petit'),' = ',F('base gran','base petita')])}`+legend([['a i b','Costat i base del petit.'],['a′ i b′','Costat i base homòlegs del gran.']])+note('El costat gran inclou el petit','Mesura des del vèrtex comú fins a l’extrem del triangle gran. No utilitzis només el tros que queda fora del petit.',true)),steps:['Busca el vèrtex comú i els costats paral·lels.','Identifica les bases petita i gran.','Escriu la proporció amb els costats sencers.','Substitueix les dades i calcula la mesura desconeguda.'],problems:[16,17,18,19,20],tip:'El costat gran inclou tot el costat petit i el tram restant.'},
escales:{section:'raons',title:'Escales: dibuix i realitat',lead:'Aplicació de la raó de longitud · Llegeix un plànol o un mapa.',body:panel('Què significa 1:100?',`<p><strong>1:100</strong> indica que 1 cm al dibuix representa <strong>100 cm a la realitat</strong>.</p><p>Comparem les longituds en la mateixa unitat.</p>${f(['Escala = ',F('longitud dibuix','longitud real')])}`+legend([['longitud dibuix','Mesura del plànol, mapa o maqueta.'],['longitud real','Mesura de l’objecte a la realitat.'],['1:100','Una unitat al dibuix representa 100 unitats reals.']]))+panel('De centímetres a metres',`<p>Una paret fa 3 cm al plànol a escala 1:100:</p>${f(['longitud real = 3 · 100 = 300 cm'])}${f(['300 cm · ',F('1 m','100 cm'),' = 3 m'])}<p><strong>1 m = 100 cm</strong> i <strong>1 km = 100 000 cm</strong>.</p>`),steps:['Llegeix l’escala i la mesura del dibuix.','Multiplica la mesura del dibuix pel nombre que hi ha després de 1:.','El resultat conserva la unitat del dibuix.','Converteix els centímetres si et demanen metres o quilòmetres.'],problems:[62,70],tip:'Primer troba la longitud real en centímetres. Després converteix-la a la unitat que et demanen.'},
area:{section:'raons',title:'Raó de semblança d’àrea',lead:'Missió 9 · Descobreix com canvia la superfície.',body:panel('L’àrea té dues dimensions',`<p>L’àrea mesura la <strong>superfície</strong>. S’expressa, per exemple, en cm² o m².</p><p>En duplicar les longituds, l’àrea es multiplica per <strong>2² = 4</strong>.</p>${squares}`)+panel('Les fórmules dels apunts',`<p>En aquests apunts, ${ra} és <strong>el factor de longitud calculat a partir de les àrees</strong> de dues figures semblants.</p><p>El seu quadrat indica per quant es multiplica l’àrea.</p>${f(['('+ra+')² = ',F('àrea final','àrea inicial')])}${f(['àrea final = àrea inicial · ('+ra+')²'])}${f([ra+' = ',R(F('àrea final','àrea inicial'))])}`+legend([[ra,'Factor de longitud. Es calcula amb una arrel quadrada. No té unitats.'],['('+ra+')²','Factor pel qual es multiplica l’àrea.'],['àrea inicial','Superfície de la figura inicial.'],['àrea final','Superfície de la figura final.']])+note('La raó i el seu quadrat',`Si ${ra} = 2, l’àrea es multiplica per <strong>2² = 4</strong>. Les àrees han d’estar en la mateixa unitat.`,true))+panel('L’arrel quadrada',`<p>L’arrel quadrada de 9 és <strong>3</strong>, perquè <strong>3 · 3 = 9</strong>.</p><p>A la calculadora, busca la funció <strong>√</strong>. Comprova el resultat multiplicant-lo per si mateix.</p>`),steps:['Identifica les dades: àrea inicial i raó, o dues àrees.','Per trobar l’àrea final, eleva la raó al quadrat.','Multiplica l’àrea inicial pel resultat.','Si busques la raó, divideix àrea final entre inicial i fes l’arrel quadrada.'],problems:[41,42,43,44,45],tip:'Primer calcula el quadrat de la raó. Després multiplica l’àrea inicial. Escriu cm² o m² a la resposta.'},
volum:{section:'raons',title:'Raó de semblança de volum',lead:'Missió 10 · Descobreix com canvia l’espai que ocupa un cos.',body:panel('El volum té tres dimensions',`<p>El volum mesura <strong>l’espai que ocupa un cos</strong>. S’expressa en cm³ o m³.</p><p>En duplicar les longituds, el volum es multiplica per <strong>2³ = 8</strong>.</p>${cubes}`)+panel('Les fórmules dels apunts',`<p>En aquests apunts, ${rv} és <strong>el factor de longitud calculat a partir dels volums</strong> de dos cossos semblants.</p><p>El seu cub indica per quant es multiplica el volum.</p>${f(['('+rv+')³ = ',F('volum final','volum inicial')])}${f(['volum final = volum inicial · ('+rv+')³'])}${f([rv+' = ',R(F('volum final','volum inicial'),3)])}`+legend([[rv,'Factor de longitud. Es calcula amb una arrel cúbica. No té unitats.'],['('+rv+')³','Factor pel qual es multiplica el volum.'],['volum inicial','Espai que ocupa el cos inicial.'],['volum final','Espai que ocupa el cos final.']])+note('Conserva el cub',`Si ${rv} = 2, multipliquem per <strong>2 · 2 · 2 = 8</strong>. Els dos volums han d’estar en la mateixa unitat.`,true))+panel('L’arrel cúbica amb la calculadora',`<p>L’arrel cúbica de 8 és <strong>2</strong>, perquè <strong>2 · 2 · 2 = 8</strong>.</p><ol class="step-list"><li><div>Calcula <strong>volum final : volum inicial</strong>.</div></li><li><div>Busca <strong>∛</strong> a la calculadora. La tecla i l’ordre depenen del model.</div></li><li><div>Si no hi ha ∛, utilitza <strong>resultat ^ (1 : 3)</strong>. Escriu els parèntesis.</div></li><li><div>Comprova el resultat multiplicant-lo <strong>tres vegades</strong>.</div></li></ol><p>Per exemple: <strong>8 ^ (1 : 3) = 2</strong>.</p>`),steps:['Identifica les dades: volum inicial i raó, o dos volums.','Per trobar el volum final, eleva la raó al cub.','Multiplica el volum inicial pel resultat.','Si busques la raó, divideix volum final entre inicial i fes l’arrel cúbica.'],problems:[46,47,48,49,50],tip:'Elevar al cub és multiplicar el nombre per si mateix tres vegades. Escriu cm³ o m³ a la resposta.'},
catet:{section:'teoremes',title:'Teorema del catet',lead:'Missió 5 · Troba un catet a partir de la seva projecció.',body:panel('El triangle rectangle',`<p>Té <strong>un angle de 90°</strong>. Els <strong>catets b i c</strong> formen aquest angle.</p><p>La <strong>hipotenusa a</strong> és el costat oposat i el més llarg.</p>${right}`)+panel('L’altura divideix la hipotenusa',`<p>L’altura <strong>h</strong> surt del vèrtex de l’angle recte i forma 90° amb la hipotenusa.</p><p>La divideix en <strong>m i n</strong>: són les projeccions dels catets.</p>${altitude}${f(['a = m + n'])}`)+panel('Les fórmules',`${f(['b² = a · m'])}${f(['c² = a · n'])}<p>Multipliquem <strong>la hipotenusa sencera per la projecció del catet</strong>. Després fem l’arrel quadrada.</p>`+legend([['a','Hipotenusa sencera.'],['b i c','Catets.'],['m','Projecció del catet b.'],['n','Projecció del catet c.'],['h','Altura sobre la hipotenusa.']])+note('Cada catet amb la seva projecció','Per trobar b utilitzem m. Per trobar c utilitzem n.',true)),steps:['Identifica la hipotenusa a i el catet desconegut.','Busca la seva projecció: m per a b, o n per a c.','Multiplica hipotenusa per projecció.','Fes l’arrel quadrada del producte.'],problems:[21,22,23,24,25],tip:'Si b² = 36, aleshores b = 6, perquè 6 · 6 = 36.'},
altura:{section:'teoremes',title:'Teorema de l’altura',lead:'Missió 6 · Troba l’altura sobre la hipotenusa.',body:panel('Quina altura busquem?',`<p>L’altura <strong>h</strong> surt del vèrtex de l’angle recte. És <strong>perpendicular a la hipotenusa</strong>.</p><p>La hipotenusa queda dividida en <strong>m i n</strong>.</p>${altitude}`)+panel('Les fórmules',`${f(['h² = m · n'])}${f(['h = ',R('m · n')])}<p>Multipliquem els dos segments. Després fem <strong>l’arrel quadrada</strong>.</p>`+legend([['h','Altura sobre la hipotenusa.'],['m i n','Segments en què l’altura divideix la hipotenusa.'],['a','Hipotenusa sencera: a = m + n.'],['b i c','Catets.']])+note('Necessitem m i n','Per calcular l’altura amb aquest teorema, multipliquem els segments de la hipotenusa. No els catets.',true)),steps:['Comprova que és un triangle rectangle.','Identifica m i n sobre la hipotenusa.','Multiplica m · n.','Fes l’arrel quadrada del producte.'],problems:[26,27,28,29,30],tip:'m i n són dos trossos de la hipotenusa. L’altura h forma 90° amb aquesta.'},
pitagores:{section:'teoremes',title:'Teorema de Pitàgores',lead:'Missió 7 · Troba la hipotenusa o un catet.',body:panel('Només en triangles rectangles',`<p>Ha de tenir <strong>un angle de 90°</strong>.</p><p><strong>a és la hipotenusa</strong>. <strong>b i c són els catets</strong>.</p>${right}`)+panel('La fórmula principal',`${f(['a² = b² + c²'])}<p>El quadrat de la hipotenusa és igual a <strong>la suma dels quadrats dels catets</strong>.</p>`+legend([['a','Hipotenusa: costat més llarg, oposat a l’angle recte.'],['b i c','Catets: formen l’angle de 90°.'],['²','Al quadrat: multipliquem el nombre per si mateix.'],['√','Arrel quadrada: el nombre positiu que, multiplicat per si mateix, dona el valor de dins.']]))+panel('Busquem la hipotenusa',`<p>Elevem els catets al quadrat. <strong>Sumem</strong> i fem l’arrel quadrada.</p>${f(['a = ',R('b² + c²')])}`)+panel('Busquem un catet',`<p>Elevem la hipotenusa i el catet conegut al quadrat. <strong>Restem</strong> i fem l’arrel quadrada.</p>${f(['b = ',R('a² - c²')])}${f(['c = ',R('a² - b²')])}`+note('Comprova la resposta','La hipotenusa ha de ser més llarga que qualsevol catet. Totes les mesures han d’estar en la mateixa unitat.',true)),steps:['Marca l’angle de 90° i identifica la hipotenusa a.','Decideix què busques: hipotenusa o catet.','Eleva les dades al quadrat. Suma per a la hipotenusa; resta per al catet.','Fes l’arrel quadrada i escriu la unitat.'],problems:[31,32,33,34,35],tip:'3² no és 3 · 2. És 3 · 3 = 9. Acaba fent l’arrel quadrada per trobar la longitud.'}
};
})();
